export const ROLE = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  TEACHING_ASSISTANT: 'TEACHING_ASSISTANT',
  PARENT: 'PARENT',
  GUEST: 'GUEST'
}